#!/bin/bash -x
cd ~/pettil/tools
rm -v *.dmp kosmon-5*.* kosmon-9*.* t.dif
xa -DBASE=5000 -DPETB2 -o kosmon-5000.b2 kosmon.a65
xa -DBASE=5000 -DPETB4 -o kosmon-5000.b4 kosmon.a65
xa -DBASE=5000 -DPET80 -o kosmon-5000.80 kosmon.a65
xa -DBASE=9000 -DPETB2 -o kosmon-9000.b2 kosmon.a65
xa -DBASE=9000 -DPETB4 -o kosmon-9000.b4 kosmon.a65
xa -DBASE=9000 -DPET80 -o kosmon-9000.80 kosmon.a65

hd -v kosmon-3032.prg    > pre5b2.dmp
hd -v kosmon-4032.prg    > pre5b4.dmp
hd -v kosmon-8032.prg    > pre580.dmp
hd -v kosmon\$9-3032.prg > pre9b2.dmp
hd -v kosmon\$9-4032.prg > pre9b4.dmp
hd -v kosmon\$9-8032.prg > pre980.dmp

hd -v kosmon-5000.b2 > kosmon5b2.dmp
hd -v kosmon-5000.b4 > kosmon5b4.dmp
hd -v kosmon-5000.80 > kosmon580.dmp
hd -v kosmon-9000.b2 > kosmon9b2.dmp
hd -v kosmon-9000.b4 > kosmon9b4.dmp
hd -v kosmon-9000.80 > kosmon980.dmp

diff -s pre5b2.dmp kosmon5b2.dmp >> t.dif
diff -s pre5b4.dmp kosmon5b4.dmp >> t.dif
diff -s pre9b4.dmp kosmon9b4.dmp >> t.dif
diff -s pre580.dmp kosmon580.dmp >> t.dif
diff -s pre980.dmp kosmon980.dmp >> t.dif
diff -s pre9b2.dmp kosmon9b2.dmp >> t.dif
subl t.dif
