#!/bin/bash
# ~/pettil/tools/mkperturb
#
cd ~/pettil >/dev/null

pets=$(pgrep -x x\(pet\|vic\|64sc\|128\|plus4\))
while [ "${pets}" ]; do
    echo -n .
    sleep 1
    pets=$(pgrep -x x\(pet\|vic\|64sc\|128\|plus4\))
done
echo

date -Iseconds >> ./perturb.log

for object in ./tmp/perturb/perturb.*.png
do
    cheese=$(basename ${object#*/})

    if [ ! -f data/perturb/${cheese} ]; then
        echo -e "fail 🍅 ${cheese}\t-- not in data/perturb!"                                    \
        >> ./perturb.log
    fi

    diff -s -b ./tmp/perturb/${cheese} ./data/perturb/                          \
    |sed 's/^.*\/\(.*\)\ are\ identical$/pass 🥑 \1/'                                \
    |sed 's/^.*\/\(.*\)\ differ$/fail 🍅 \1 \t\t...different!/'                      \
    >> ./perturb.log
done

for object in ./data/perturb/perturb.*.png
do
    cheese=$(basename ${object#*/})
    echo ${cheese}
    if [ ! -f tmp/perturb/${cheese} ]; then
        echo -e "fail 🍅 ${cheese}\t-- not in tmp/perturb!"                                    \
        >> ./perturb.log
    fi
done
exit
