#!/bin/sh
# pettil/tools/lsperturb

cd ~/pettil >/dev/null

#for a in $(ls ./tmp/perturb/*.scrsh.png)
#for a in $(find . -type f -name "*.scrsh.png" | sort)
#do
#    b=$(basename $a)
#    echo $b
#    display -delay 30 -resize '150%' -geometry '+60+260' tmp/perturb/$b &
#    display -delay 30 -resize '150%' -geometry '+60+32' data/perturb/$b &
#    sleep 1
#done
for a in $(find . -name "*.scrsh.png" -print0 \
    | xargs -0 -I {} basename {} \
    | sort -u)
do
    echo $a
    display -delay 30 -resize '120%' -geometry '+60+80' tmp/perturb/$a &
    display -delay 30 -resize '120%' -geometry '+560+80' data/perturb/$a &
    grep $a perturb.log | tail -1
    sleep $1
done

exit
