#!/bin/sh
# pettil/tools/lsperturb

cd ~/pettil >/dev/null

#for a in $(ls ./tmp/perturb/*.scrsh.png)
#for a in $(find . -type f -name "*.scrsh.png" | sort)
#do
#    b=$(basename $a)
#    echo $b
#    display -delay 30 -resize '150%' -geometry '+60+260' tmp/perturb/$b &
#    display -delay 30 -resize '150%' -geometry '+60+32' data/perturb/$b &
#    sleep 1
#done
for a in $(find . -name "*.scrsh.png" -print0 \
    | xargs -0 -I {} basename {} \
    | sort -u)
do
    echo $a
    display -delay 01 -resize '120%' -geometry '+540-250' data/perturb/$a 2>/dev/null &
    display -delay 01 -resize '120%' -geometry '+20-250' tmp/perturb/$a 2>/dev/null &
    grep $a perturb.log | tail -1
    if [ ! -z ${VIDEOSLOWDOWN+0} ]
    then
        sleep ${VIDEOSLOWDOWN}
    fi
done

exit
