#!/bin/bash
# ~/pettil/tools/mkfeats
#
cd ~/pettil >/dev/null
rm -vf ./tmp/perturb/perturb.?-*.scrsh.png
timeout=20

# for each PERTURB target that was built by `mkperturb`
for disturbance in ./obj/perturb/perturb-*.?
do
    feat=$(basename "${disturbance#*/}")
    targetid="${disturbance: -1}"
    ls -l ./obj/perturb/${feat}
    echo "$(ls -l ./obj/perturb/${feat}) ${feat} ${targetid}"
    DISPLAY=":0.0" PERTURB="${feat}" timeout ${timeout} ./tools/mkpet2 ${targetid}
done
# return our images
echo -n "${HOSTNAME} "
case $HOSTNAME in
  samosa)
    echo "sending images"
    scp -r ./tmp/perturb/*.scrsh.png tarabuza:pettil/tmp/perturb/
    DISPLAY=":0.0" ./tools/lsperturb 2
    ;;
  tarabuza)
    echo
    ;;
  *)
    echo " where am I?"
    ;;
esac

# append this performance to perturb.log
./tools/chkperturb

exit
