#!/bin/bash
# ~/pettil/tools/mkfeats
#
cd ~/pettil >/dev/null
while true
do
    LOCAL=$(git rev-parse HEAD)
    REMOTE=$(git rev-parse ${u})
    echo $LOCAL
    echo $REMOTE
    if [ "${LOCAL}" != "${REMOTE}" ]; then
        git fetch tarabuza

        rm -vf ./tmp/perturb/perturb.?-*.scrsh.png
        timeout=20

        # for each PETTIL target that was built by `mkpettil`
        for disturbance in ./obj/perturb/*.?
        do
            feat=$(basename "${disturbance#*/}")
            targetid="${disturbance: -1}"
            cheese="${disturbance#*/}"
            ls -l ./obj/perturb/${feat}
            PERTURB="${cheese}" timeout ${timeout} ./tools/mkpet2 ${targetid}
        done
        scp -r ./tmp/perturb/*.scrsh.png tarabuza:pettil/tmp/perturb/
    fi
    sleep 5
done
exit

