#!/bin/bash -x
# ~/pettil/tools/mkfeats
#
cd ~/pettil >/dev/null
rm -vf ./tmp/perturb/perturb.?-*.scrsh.png
timeout=20

# for each PERTURB target that was built by `mkperturb`
for disturbance in ./obj/perturb/perturb-*.?
do
    feat=$(basename "${disturbance#*/}")
    targetid="${disturbance: -1}"
    ls -l ./obj/perturb/${feat}
    echo "$(ls -l ./obj/perturb/${feat}) ${feat} ${targetid}"
    DISPLAY=":0.0" PERTURB="${feat}" timeout ${timeout} ./tools/mkpet2 ${targetid}
done
# return our images
scp -r ./tmp/perturb/*.scrsh.png tarabuza:pettil/tmp/perturb/
# append this performance to perturb.log
./tools/chkperturb
# lsperturb - display them side-by-side on the Pi
DISPLAY=":0.0" ./tools/lsperturb 2

exit
