#!/bin/bash

# pettil/tools/mkpet
# target  mask  machine
#   0        1  PET #700251
#   1        2  Upgrade PET
#   2        4  4.0 PET
#   3        8  80-column PET
#           16  Plus/4
#   4       32  VIC-20
#   5       64  Commodore 64
#          128  Commodore 128

cd ~/pettil/

if [ "`hostname`" = "samosa" ]; then
    export PERTURBTERMINAL="lxterminal --geometry=80x41 -e "
else
    export PERTURBTERMINAL="xfce4-terminal --geometry=80x41-4-4 --zoom=0 -e "
fi

for arg in "$@"
do
    if [ -z "${PERTURB+xxx}" ]
     then moncommand=obj/pettil.mon${arg}
     else moncommand=obj/perturb/${PERTURB}.mon${arg}
        timeout="timeout 30 "
#        exitscrsh="-exitscreenshot tmp/perturb/${PERTURB}.screx${arg} "
        if [ "${arg}" == 7 ]
        then
                exitscrsh="-exitscreenshotvicii tmp/perturb/${PERTURB}.screx${arg} "
        fi
    fi

    case $arg in
# 0 (PET 2001-N #700251)
        "0" )
            export ADDR='0401'
        nohup ${timeout} \
        xpet ${exitscrsh}    \
        -moncommand ${moncommand}                                                \
        -config data/sdl2_chitselb.vicerc \
        -iosize 2048 -petdww -petdwwimage data/dwwimage.dww \
        -8 chitselb.d64                 \
        -9 pettil.d64                   \
        -warp
           ;;

# 1 (PET 3032 Upgrade ROM)
        "1" )
            export ADDR='0401'
        nohup ${timeout} \
        xpet ${exitscrsh}    \
        -moncommand ${moncommand}                                                \
        -config data/sdl2_pet3.vicerc \
        -iosize 2048 -petdww -petdwwimage data/dwwimage.dww \
        -8 chitselb.d64                 \
        -9 pettil.d64                   \
        -warp
           ;;

# 2 (PET 4032 4.0 ROM)
        "2" )
            export ADDR='0401'
        nohup ${timeout} \
        xpet ${exitscrsh}    \
        -moncommand ${moncommand}                                               \
        -config data/sdl2_pet4.vicerc \
        -iosize 2048 -petdww -petdwwimage data/dwwimage.dww \
        -8 chitselb.d64                 \
        -9 pettil.d64                   \
        -warp
           ;;

# 3 (PET 8032 4.0 ROM)
        "3" )
            export ADDR='0401'
        nohup ${timeout} \
        xpet ${exitscrsh}    \
        -moncommand ${moncommand}                                               \
        -config data/sdl2_pet80.vicerc                                          \
        -iosize 2048 -petdww -petdwwimage data/dwwimage.dww                     \
        -8 chitselb.d64                                                         \
        -9 pettil.d64                                                           \
        -warp
           ;;

# 4 (VIC-20 expanded)
        "4" )
            export ADDR='1201'
        nohup ${timeout} \
        xvic ${exitscrsh}                       \
        -moncommand ${moncommand}                                               \
        -config data/sdl2_chitselb.vicerc                                       \
        -8 chitselb.d64                                                         \
        -9 pettil.d64                                                           \
        -warp
           ;;

# 5 (C=64)
        "5" )
            export ADDR='0801'
        nohup ${timeout} \
        x64sc ${exitscrsh}                      \
        -moncommand ${moncommand}                                               \
        -config data/sdl2_chitselb.vicerc                                       \
        -8 chitselb.d64                                                         \
        -9 pettil.d64                                                           \
        -warp
           ;;

# 6 (C128)
        "6" )
            export ADDR='1C01'
        nohup ${timeout} \
        x128 ${exitscrsh}                       \
        -moncommand ${moncommand}                                               \
        -config data/sdl2_chitselb.vicerc \
        -8 chitselb.d64                 \
        -9 pettil.d64                   \
        -warp
           ;;

# 7 (Plus/4)
        "7" )
            export ADDR='1001'
        nohup ${timeout} \
        xplus4 ${exitscrsh}                     \
        -moncommand ${moncommand}                                               \
        -config data/sdl2_chitselb.vicerc                                       \
        -8 chitselb.d64                                                         \
        -9 pettil.d64                                                           \
        -warp
           ;;
    esac
done
exit
