#!/bin/bash
cd ~/pettil/
for arg in "$@"
do
    case $arg in
        "0" )
            export ADDR='0401'
#            export MONCOMMAND='pettil.mon0'
    xfce4-terminal --command="xpet      \
        -moncommand obj/pettil.mon$$arg        \
        -config data/sdl2_chitselb.vicerc \
        -iosize 2048 -petdww -petdwwimage data/dwwimage.dww \
        -8 chitselb.d64                 \
        -9 pettil.d64                   \
        -warp" &
           ;;
#            export ADDR='0401';;
        "4" )
            export ADDR='1201'
    xfce4-terminal --command="xvic      \
        -moncommand obj/pettil.mon$$arg     \
        -config data/sdl2_chitselb.vicerc \
        -8 chitselb.d64                 \
        -9 pettil.d64                   \
        -warp" &
           ;;
#            echo more;
#            export ADDR='1201';;
        "5" )
            export ADDR='0801'
           ;;
#            export ADDR='0801';;
        "--first" )
           START_DATE=$arg;;
        "--last" )
           END_DATE=$arg;;
        "--copy" )
           COPY=true;;
        "--remove" )
           REMOVE=true;;

# ... and so on
    esac
done
exit

#
#    1 PET #700251
#    2 Upgrade PET
#    4 4.0 PET
#    8 80-column PET
#   16 Plus/4
#   32 VIC-20
#   64 Commodore 64
#  128 Commodore 128
