#!/bin/bash
# pettil/tools/mkpet2
#
# for when you need a Rack-o-PETs

cd ~/pettil/ >/dev/null

targetid="${PERTURB: -1}"
mfile="${PERTURB::-1}mon${targetid}"

echo "$mfile"   "$targetid"
for arg in "$@"
do
    moncommand="-moncommand ./obj/perturb/${mfile}"
#    exitscrsh="-exitscreenshotvicii tmp/perturb/${PERTURB}.screx${arg} "

    case $arg in
# 0 (PET 2001-N #700251)
        "0" )
            export ADDR='0401'
            xpet ${exitscrsh} ${moncommand} -8 chitselb.d64 -9 pettil.d64      \
            -iosize 2048 -petdww -petdwwimage data/dwwimage.dww                 \
            -config data/sdl2_chitselb.vicerc -warp
           ;;

# 1 (PET 3032 Upgrade ROM)
        "1" )
            export ADDR='0401'
            xpet ${exitscrsh} ${moncommand} -8 chitselb.d64 -9 pettil.d64      \
            -iosize 2048 -petdww -petdwwimage data/dwwimage.dww                 \
            -config data/sdl2_pet3.vicerc
           ;;

# 2 (PET 4032 4.0 ROM)
        "2" )
            export ADDR='0401'
            xpet ${exitscrsh} ${moncommand} -8 chitselb.d64 -9 pettil.d64      \
            -iosize 2048 -petdww -petdwwimage data/dwwimage.dww                 \
            -config data/sdl2_pet4.vicerc
           ;;

# 3 (PET 8032 4.0 ROM)
        "3" )
            export ADDR='0401'
            xpet ${exitscrsh} ${moncommand} -8 chitselb.d64 -9 pettil.d64      \
            -iosize 2048 -petdww -petdwwimage data/dwwimage.dww                 \
            -config data/sdl2_pet80.vicerc
           ;;

# 4 (VIC-20 expanded)
        "4" )
            export ADDR='1201'
            xvic ${moncommand} -8 chitselb.d64 -9 pettil.d64 -warp     \
            -config data/sdl2_chitselb.vicerc
           ;;

# 5 (C=64)
        "5" )
            export ADDR='0801'
            x64sc ${moncommand} -8 chitselb.d64 -9 pettil.d64 -warp     \
            -config data/sdl2_chitselb.vicerc
           ;;

# 6 (C128)
        "6" )
            export ADDR='1C01'
            x128 ${moncommand} -8 chitselb.d64 -9 pettil.d64 -warp     \
            -config data/sdl2_chitselb.vicerc  ${exitscrsh}
           ;;

# 7 (Plus/4)
        "7" )
            export ADDR='1001'
            xplus4 ${moncommand} -8 chitselb.d64 -9 pettil.d64 -warp     \
            -config data/sdl2_chitselb.vicerc
           ;;
    esac
done
exit
