#!/bin/bash
cd ~/pettil/
sh ./tools/buildpettil.sh 0 5 6400 0401
sh ./tools/buildpettil.sh 1 5 5E00 0401
sh ./tools/buildpettil.sh 2 5 4F00 0401 MICROMON
#sh ./tools/buildpettil.sh 3 2 6400 0401
#sh ./tools/buildpettil.sh 3 4 6400 0401
#sh ./tools/buildpettil.sh 4 4 5E00 0401
#sh ./tools/buildpettil.sh 5 4 4F00 0401
