#!/bin/bash -x

# pettil/tools/mkpet
# target  mask  machine
#   0        1  PET #700251
#   1        2  Upgrade PET
#   2        4  4.0 PET
#   3        8  80-column PET
#           16  Plus/4
#   4       32  VIC-20
#   5       64  Commodore 64
#          128  Commodore 128

cd ~/pettil/ >/dev/null

echo $PERTURB
timeout=4

for arg in "$@"
do
    moncommand="-moncommand ./obj/perturb/${PERTURB}.mon${arg}"
#    exitscrsh="-exitscreenshotvicii tmp/perturb/${PERTURB}.screx${arg} "

    case $arg in
# 0 (PET 2001-N #700251)
        "0" )
            export ADDR='0401'
            timeout ${timeout} \
            xpet ${exitscrsh} ${moncommand} -8 chitselb.d64 -9 pettil.d64      \
            -iosize 2048 -petdww -petdwwimage data/dwwimage.dww                 \
            -config data/sdl2_chitselb.vicerc -warp
           ;;

# 1 (PET 3032 Upgrade ROM)
        "1" )
            export ADDR='0401'
            timeout ${timeout} \
            xpet ${exitscrsh} ${moncommand} -8 chitselb.d64 -9 pettil.d64      \
            -iosize 2048 -petdww -petdwwimage data/dwwimage.dww                 \
            -config data/sdl2_pet3.vicerc
           ;;

# 2 (PET 4032 4.0 ROM)
        "2" )
            export ADDR='0401'
            timeout ${timeout} \
            xpet ${exitscrsh} ${moncommand} -8 chitselb.d64 -9 pettil.d64      \
            -iosize 2048 -petdww -petdwwimage data/dwwimage.dww                 \
            -config data/sdl2_pet4.vicerc
           ;;

# 3 (PET 8032 4.0 ROM)
        "3" )
            export ADDR='0401'
            timeout ${timeout} \
            xpet ${exitscrsh} ${moncommand} -8 chitselb.d64 -9 pettil.d64      \
            -iosize 2048 -petdww -petdwwimage data/dwwimage.dww                 \
            -config data/sdl2_pet80.vicerc
           ;;

# 4 (VIC-20 expanded)
        "4" )
            export ADDR='1201'
            timeout ${timeout} \
            xvic ${moncommand} -8 chitselb.d64 -9 pettil.d64 -warp     \
            -config data/sdl2_chitselb.vicerc
           ;;

# 5 (C=64)
        "5" )
            export ADDR='0801'
            timeout ${timeout} \
            x64sc ${moncommand} -8 chitselb.d64 -9 pettil.d64 -warp     \
            -config data/sdl2_chitselb.vicerc
           ;;

# 6 (C128)
        "6" )
            export ADDR='1C01'
            timeout ${timeout} \
            x128 ${moncommand} -8 chitselb.d64 -9 pettil.d64 -warp     \
            -config data/sdl2_chitselb.vicerc  ${exitscrsh}
           ;;

# 7 (Plus/4)
        "7" )
            export ADDR='1001'
            timeout ${timeout} \
            xplus4 ${moncommand} -8 chitselb.d64 -9 pettil.d64 -warp     \
            -config data/sdl2_chitselb.vicerc
           ;;
    esac
done
exit
