#!/bin/bash
cd ~/pettil/
#
#    1 PET #700251
#    2 Upgrade PET
#    4 4.0 PET
#    8 80-column PET
#   16
#   32 VIC-20
#   64 Commodore 64
#  128 Commodore 128
#                        targ# romopts tdict basic
sh ./tools/buildpettil.sh 0     2       6400  0401  # upgrade rom
sh ./tools/buildpettil.sh 1     5       6400  0401  # my pet #700251
sh ./tools/buildpettil.sh 2     4       6400  0401  # 4.0 rom
sh ./tools/buildpettil.sh 3     12      6400  0401 # 80 column
sh ./tools/buildpettil.sh 4     32      6400  1201 # VIC20-01235

