#!/bin/bash -x
# ~/pettil/tools/mkperturb
#
cd ~/pettil

for pettilobj in obj/pettil.prg?
do
    pettiladdr=$(dd  bs=1 count=2 conv=swab status=none <${pettilobj} | xxd -p)
    padr=$(echo "obase=10;ibase=16;${pettiladdr}"|bc)
    targetid=${pettilobj: -1}
    objsize=$(stat -c'%s' ${pettilobj})
    perturb=$(echo "${objsize} + ${padr}"|bc)
    badr=$(echo "obase=16;ibase=10;${perturb}-2"|bc)
    for tricks in $(ls -d src/perturb/*/)
    do
        cheese=$(basename ${tricks#*/})
        feat="perturb-${cheese}"
        case ${targetid} in
            0)
                echo "my PET!"
                romopts=5
                hitop=6300
                vpet=xpet
                abend=E089
                ;;
            4)
                echo "VIC-20!"
                romopts=32
                hitop=6300
                vpet=xvic
                abend=E089
                ;;
        esac
        echo targetid: ${targetid}
        echo tricks: ${tricks}
        echo
        echo pettilobj: ${pettilobj}
        echo pettiladdr: ${pettiladdr}
        echo padr: ${padr}
        echo badr: ${badr}
        echo objsize: ${objsize}
        echo perturb: ${perturb}
        echo cheese: ${cheese}
        echo feat: ${feat}
        echo romopts: ${romopts}
        echo hitop: ${hitop}
        echo
#        foo=`echo "obase=10;ibase=16;$(hexdump -e '"%04x"' -n2 ${pettilobj})"|bc`
        pwd
        ls ./src/perturb/${cheese}/*.i65  ./tmp/perturb/${feat}.a65
        cat ./src/perturb/${cheese}/*.i65> ./tmp/perturb/${feat}.a65
        cd ./tmp/perturb/
        xa ${feat}.a65                                                     \
            -DPERTURB=${feat}                                              \
            -DPERTURBORG=${perturb}                                             \
            -DROM_OPTIONS=${romopts}                                            \
            -DHITOP=${hitop}                                                    \
            -DSPECIALOPTS=${load}                                               \
            -I ../../src/common/                                                \
            -I ../                                                              \
            -o ../../obj/perturb/${feat}.prg${targetid}                    \
            -e ../${feat}.err${targetid}                                   \
            -l ../${feat}.lab${targetid}                                   \
            -v
        cd -
        echo "LD addr: $(egrep -l ^LD, ./tmp/*.lab${targetid})"
        # (`10 sys1037` BASIC hook & JMP(indirect) opcode)
        # 0401 0B 04 0A 00 9E 31 30 33 37 00 00 00 6C
        dd bs=1 if=${pettilobj} status=none     of=tmp/t.1 skip=0 count=15
        # replacement `perturb` address
        echo -e -n "\x${badr:2:2}\x${badr:0:2}"  > tmp/t.2
        # the rest of the original PETTIL binary
        dd bs=1 if=${pettilobj} status=none     of=tmp/t.3 skip=17
#       echo "bk E089\ncommand 9 \"scrsh \\\"perturb/${namer}.scrsh\\\" 2;quit\"\nkeybuf load\"${cheese}\",9\x0drun\x0d" >> tmp/perturb.mon4
#\\ncommand 9 \\"scrsh \\\\"perturb\/%s.scrsh\\\" 2;quit\\"\\nkeybuf  load\\"${cheese}\\",9\\x0drun\\x0d\
        awk -F,                                                                 \
            -v feat=${feat}                                               \
            -v target=${targetid}                                               \
            -v abend=${abend}                                             \
            -v petcommand="load \"xyzzy\""                                      \
                'BEGIN {                                                        \
                    printf("; %s\n", feat)                                     \
                }                                                               \
                {                                                               \
                    printf("al C:%4s .%s\n", substr($2,4,4), $1)                \
                }                                                               \
                END {                                                           \
                    print "bk .disp1  ;dis 1";                                  \
                    print "bk .disp2  ;dis 2";                                  \
                    print "bk .disp3  ;dis 3";                                  \
                    print "bk .nexto  ;dis 4";                                  \
                    print "bk .exit   ;dis 5";                                  \
                    print "bk .restart;dis 6";                                  \
                    print "bk .plugh";                                          \
                    print "bk .xyzzy";                                          \
                    printf("bk %4s\n",abend);                                   \
                    printf("command 9 \"scrsh \\\"%s.scrsh\\\" 2;quit\"\n",     \
                     feat);                                                     \
                    printf("keybuf load\"%s.%s\",9\\x0drun\\x0d\n",             \
                     feat, target);                                             \
                    print "; stack sentinel value, VICE first time is dicey ";  \
                    print "watch store 7f if a != 10";                          \
                    print "watch store 4f if a != 01";                          \
                }'                                                              \
            ./tmp/${feat}.lab${targetid} >                                 \
            ./obj/perturb/${feat}.mon${targetid}

        # save original `startup` address like so:
        # unneeded because PERTURB source includes PETTIL labels
        # dd bs=1 if=${pettilobj} status=none   of=tmp/t.0 skip=15 count=2

        cat tmp/t.1 tmp/t.2 tmp/t.3 obj/perturb/${feat}.prg${targetid} \
            > obj/perturb/${feat}.${targetid}
#        dd bs=1 if=${pettilobj} of=perturb/${cheese}.${targetid}skip=15 count=2 status=none
#        dd if=${pettilobj} of=perturb/perturb-${cheese}.${targetid} bs=1 count=13
#        echo "AA" >> perturb/perturb-${cheese}.${targetid}
#        dd if=${pettilobj} of=perturb/perturb-${cheese}.${targetid} bs=1 count=13
        c1541                           \
            -attach ./pettil.d64       \
            -write obj/perturb/${feat}.${targetid} \
            -dir
        echo $feat
        echo $targetid
        xfce4-terminal --command="${vpet}                                       \
            -moncommand obj/perturb/${feat}.mon${targetid}                      \
            -config data/sdl2_chitselb.vicerc                                   \
            -8 chitselb.d64                                                     \
            -9 pettil.d64                                                       \
            -warp"

        petproc=$(pgrep -n x\(vic\|pet\))
        echo petproc: $petproc
        ps -p ${petproc} -o comm=
        sleep 4
        kill -9 ${petproc}
    done
done
echo +++ obj/ contents:
ls -laR obj/
echo +++ Y2 a hollow voice says
c1541                           \
    -attach ./pettil.d64       \
    -dir
exit















for pettilobj in obj/pettil.prg?
do
    load=$(dd  bs=1 count=2 conv=swab status=none <${pettilobj} | xxd -p)
    echo load addr ${load}
    targetid=${pettilobj: -1}
    echo "targetid $targetid"
#    pertub=$(echo "ibase=10;obase=16;$(echo `stat -c'%s' ${pettilobj}` "+" `echo "obase=10;ibase=16;$(hd -e '"%04x"' -n2 ${pettilobj})"|bc`|bc)"|bc)
    objsize=$(stat -c'%s' ${pettilobj})
    objaddr=$(echo "obase=10;ibase=16;$(hexdump -e '"%04x"' -n2 ${pettilobj})"|bc)
    perturb=$(echo "${objsize} + ${objaddr}"|bc)
    echo ${targetid} ${perturb} ${objsize} ${objaddr}
    for tricks in $(ls -d src/perturb/*/)
    do
        cheese=$(basename ${tricks#*/})
        feat="perturb-${cheese}"
        foo=`echo "obase=10;ibase=16;$(hexdump -e '"%04x"' -n2 ${pettilobj})"|bc`
        echo derp ${tricks} derp ${cheese} derp ${feat} derp ${foo}
        cat ./src/perturb/${cheese}/*.i65> ./tmp/perturb/${feat}.a65
        ls ${tricks}
        pwd
        cd ./tmp/perturb/
        ls -la

        case ${targetid} in
            0)
                echo "wow! my PET!"
                romopts=5
                hitop=6400
                ;;
            4)
                echo "hey! VIC-20!"
                romopts=32
                load=1201
                hitop=6300
                ;;
        esac

#            cat ${feat}.a65
echo before comment
: <<'ENDO'
removed './doc/sizes.txt'
'./tmp/sizes.csv' -> 'doc/sizes.csv4'
./tools/mkperturb
mkdir: created directory 'obj/perturb'
obj/pettil.prg0
18867 17842 1025
derp src/perturb/i/ derp i derp perturb-i derp
ENDO
echo after comment

#            cat ${feat}.a65
        xa ${feat}.a65                             \
            -DPERTURB=${feat}                      \
            -DPERTURBORG=${perturb}                     \
            -DROM_OPTIONS=${romopts}                    \
            -DHITOP=${hitop}                            \
            -DSPECIALOPTS=${load}                       \
            -I ../common/                               \
            -I ../../tmp/                               \
            -o ../../obj/perturb/${feat}.prg${targetid}      \
            -e ../../tmp/${feat}.err${targetid}    \
            -l ../../tmp/${feat}.lab${targetid}    \
            -v
        cd -
        pwd
        ls -la ./obj/perturb/${feat}.prg${targetid}
        cd obj
#        c1541 -attach ../pettil.d64 -del ${feat}.prg${targetid}
        c1541 -attach ../pettil.d64 -write ./perturb/${feat}.prg${targetid}
   done
#            cat obj/pettil-core.obj${target}                                    \
#                tmp/${feat}.obj${target} > obj/${feat}.prg${target}
#            cd obj
#                c1541 -attach ../pettil.d64 -del ${feat}.prg${target}
#                c1541 -attach ../pettil.d64 -write ${feat}.prg${target}
#            cd ..
#            c1541 -attach pettil.d64 -dir

done

























if [ 1 -eq 0 ]; then

cd ~/pettil
for a in obj/pettil.prg?
do
    echo $a
done

fi

# cd pettil

# This script usually runs the test automation in the `at` queue.
echo you are not at Y2
    pwd
    mkdir -v obj/perturb
    c1541 -attach pettil.d64 -dir
    export DISPLAY=:0
    echo -----------------
    c1541 -attach pettil.d64 -del "perturb*" -dir
    for target in 0 4
    for pettilprg in obj/pettil.prg?
    do
        pettilfile=$(basename ${pettilprg#*/})
        echo "target $target"
      #sh ./tools/buildpettil.sh 0     5       6500  0401
          case $target in
            0)
                echo "hey! a PET!"
                romopts=5
                load=0401
                hitop=6400
                ;;
            4)
                echo "VIC-20!"
                romopts=32
                load=1201
                hitop=6400
                ;;
        esac
        echo "${romopts} ${load} ${hitop}"
        for suite in `ls -d ./src/perturb/*/`
        do
            cheese=$(basename ${suite#*/})
            feat="perturb-${cheese}"
            foo=`echo "obase=10;ibase=16;$(hd -e '"%04x"' -n2 ./obj/pettil.prg${target})"|bc`
            echo feat cheese
            echo $feat $cheese $foo
            cat ./perturb/${cheese}/*.i65> ./tmp/perturb/${feat}.a65

            cd ./tmp/perturb

            xa ${feat}.a65                     \
                -DPERTURB=${feat}              \
                -DROM_OPTIONS=${romopts}            \
                -DHITOP=${hitop}                   \
                -DSPECIALOPTS=${load}               \
                -I ../../src/common                 \
                -o ./${feat}.obj${target}     \
                -e ./${feat}.err${target}     \
                -l ./${feat}.lab${target}     \
                -v
            cd -

#            cat obj/pettil-core.obj${target}                                    \
#                tmp/${feat}.obj${target} > obj/${feat}.prg${target}
            ls -la ./obj/${feat}.prg${target}
#            cd obj
#                c1541 -attach ../pettil.d64 -del ${feat}.prg${target}
#                c1541 -attach ../pettil.d64 -write ${feat}.prg${target}
#            cd ..
#            c1541 -attach pettil.d64 -dir
        done
    done

    date -Iseconds >> perturb/perturb.log
    rm -v perturb/*.scrsh.png
    for object in obj/perturb-*.prg4
    do
        cheese=$(basename ${object#*/})
        extension="${cheese##*.}"
        namer="${cheese%.*}"
        echo "chintz ${object}\n${cheese}\n${namer}"
        cp -v obj/perturb.mon4 tmp/
        echo "bk E089\ncommand 9 \"scrsh \\\"perturb/${namer}.scrsh\\\" 2;quit\"\nkeybuf load\"${cheese}\",9\x0drun\x0d" >> tmp/perturb.mon4
        tail -9 tmp/perturb.mon4
        pwd
        /home/chitselb/bin/xvic \
         -verbose \
         -directory data/VIC20/ \
         -moncommand tmp/perturb.mon4 \
         -config data/sdl2_chitselb.vicerc \
         -warp \
         -8 chitselb.d64 \
         -9 pettil.d64
        if [ ! -f perturb/${namer}.match.png ]; then
            echo "🍅 ${namer}\t-- no match!" >> perturb/perturb.log
        fi
        diff -s -b perturb/${namer}.scrsh.png perturb/${namer}.match.png        \
        |sed 's/^.*-\([ivxlcdm]*\).*differ$/🍅 \1 \t\t-- different\!/'           \
        |sed 's/^.*-\([ivxlcdm]*\).*identical$/🥑 \1 \t\t...pass/'                                       \
        >> perturb/perturb.log
    done

    for object in perturb/perturb-*.match.png
    do
        cheese=$(basename ${object#*/})
        extension="${cheese#*.}"
        namer="${cheese%%.*}"
        if [ ! -f perturb/${namer}.scrsh.png ]; then
            echo "🍅 ${namer}\t-- no scrsh!" >> perturb/perturb.log
        fi
    done
    exit
