#!/bin/bash -x
# ~/pettil/tools/mkperturb
#
cd ~/pettil
if [ ! -d obj/perturb ]; then
    mkdir -v obj/perturb
fi

for pettilobj in obj/pettil.prg?
do
    ls $pettilobj
    targetid=${pettilobj: -1}
#    pertub=$(echo "ibase=10;obase=16;$(echo `stat -c'%s' ${pettilobj}` "+" `echo "obase=10;ibase=16;$(hexdump -e '"%04x"' -n2 ${pettilobj})"|bc`|bc)"|bc)
    objsize=$(stat -c'%s' ${pettilobj})
    objaddr=$(echo "obase=10;ibase=16;$(hexdump -e '"%04x"' -n2 ${pettilobj})"|bc)
    perturb=$(echo "${objsize} + ${objaddr}"|bc)
    echo $perturb $objsize $objaddr
    for tricks in $(ls -d src/perturb/*/)
    do
        echo $tricks
    done

done
exit

if [ 1 -eq 0 ]; then

cd ~/pettil
for a in obj/pettil.prg?
do
    echo $a
done

fi

# cd pettil

# This script usually runs the test automation in the `at` queue.

    pwd
    mkdir -v obj/perturb
    c1541 -attach pettil.d64 -dir
    export DISPLAY=:0
    echo -----------------
    c1541 -attach pettil.d64 -del "perturb*" -dir
    for target in 0 4
    do
        echo "target $target"
      #sh ./tools/buildpettil.sh 0     5       6500  0401
          case $target in
            0)
                echo "hey! a PET!"
                romopts=5
                load=0401
                hitop=6400
                ;;
            4)
                echo "VIC-20!"
                romopts=32
                load=1201
                hitop=6400
                ;;
        esac
        echo "${romopts} ${load} ${hitop}"
        for suite in `ls -d ./src/perturb/*/`
        do
            cheese=$(basename ${suite#*/})
            replicant="perturb-${cheese}"
            foo=`echo "obase=10;ibase=16;$(hexdump -e '"%04x"' -n2 ./obj/pettil.prg${target})"|bc`
            echo replicant cheese
            echo $replicant $cheese $foo
            cat ./perturb/${cheese}/*.i65> ./tmp/perturb/${replicant}.a65

            cd ./tmp/perturb

#            cat ${replicant}.a65
            xa ${replicant}.a65                     \
                -DPERTURB=${replicant}              \
                -DROM_OPTIONS=${romopts}            \
                -DHITOP=${hitop}                   \
                -DSPECIALOPTS=${load}               \
                -I ../../src/common                 \
                -o ./${replicant}.obj${target}     \
                -e ./${replicant}.err${target}     \
                -l ./${replicant}.lab${target}     \
                -v
            cd -

#            cat obj/pettil-core.obj${target}                                    \
#                tmp/${replicant}.obj${target} > obj/${replicant}.prg${target}
            ls -la ./obj/${replicant}.prg${target}
#            cd obj
#                c1541 -attach ../pettil.d64 -del ${replicant}.prg${target}
#                c1541 -attach ../pettil.d64 -write ${replicant}.prg${target}
#            cd ..
#            c1541 -attach pettil.d64 -dir
        done
    done

    date -Iseconds >> perturb/perturb.log
    rm -v perturb/*.scrsh.png
    for object in obj/perturb-*.prg4
    do
        cheese=$(basename ${object#*/})
        extension="${cheese##*.}"
        namer="${cheese%.*}"
        echo "chintz ${object}\n${cheese}\n${namer}"
        cp -v obj/perturb.mon4 tmp/
        echo "bk E089\ncommand 9 \"scrsh \\\"perturb/${namer}.scrsh\\\" 2;quit\"\nkeybuf load\"${cheese}\",9\x0drun\x0d" >> tmp/perturb.mon4
        tail -9 tmp/perturb.mon4
        pwd
        /home/chitselb/bin/xvic \
         -verbose \
         -directory data/VIC20/ \
         -moncommand tmp/perturb.mon4 \
         -config data/sdl2_chitselb.vicerc \
         -warp \
         -8 chitselb.d64 \
         -9 pettil.d64
        if [ ! -f perturb/${namer}.match.png ]; then
            echo "🍅 ${namer}\t-- no match!" >> perturb/perturb.log
        fi
        diff -s -b perturb/${namer}.scrsh.png perturb/${namer}.match.png        \
        |sed 's/^.*-\([ivxlcdm]*\).*differ$/🍅 \1 \t\t-- different\!/'           \
        |sed 's/^.*-\([ivxlcdm]*\).*identical$/🥑 \1 \t\t...pass/'                                       \
        >> perturb/perturb.log
    done

    for object in perturb/perturb-*.match.png
    do
        cheese=$(basename ${object#*/})
        extension="${cheese#*.}"
        namer="${cheese%%.*}"
        if [ ! -f perturb/${namer}.scrsh.png ]; then
            echo "🍅 ${namer}\t-- no scrsh!" >> perturb/perturb.log
        fi
    done
    exit
